# Generated by Django 5.0.6 on 2024-05-18 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'additional_model',
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo_photo_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'organizations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Delta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('banner', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.ForeignKey(blank=True, db_column='OrganizationID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Teta.organizations')),
                ('user', models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Teta.users')),
            ],
            options={
                'db_table': 'events',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('allowed_number_of_users', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, db_column='EventID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Teta.events')),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(blank=True, db_column='EventID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Teta.events')),
                ('role', models.ForeignKey(blank=True, db_column='RoleID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Teta.roles')),
                ('user', models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Teta.users')),
            ],
            options={
                'db_table': 'participants',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(blank=True, max_length=6, null=True)),
                ('organization', models.ForeignKey(blank=True, db_column='OrganizationID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Teta.organizations')),
                ('user', models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Teta.users')),
            ],
            options={
                'db_table': 'organizationmembers',
                'managed': True,
            },
        ),
    ]
