# Generated by Django 5.0.6 on 2024-05-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teta', '0003_users_email'),
    ]

    operations = [

    ]
