# Generated by Django 5.0.6 on 2024-05-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teta', '0004_users_last_login_alter_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='max_participants',
            field=models.IntegerField(default=110),
        ),
    ]
