# Generated by Django 5.0.6 on 2024-05-20 06:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teta', '0005_events_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='registration_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),

    ]
